export const Questions = [
  {
     propmt:"What is the name of Alex's first Boyfriend?",
     optionA:"Arjun",
     optionB:"Sanjay",
     optionC:"Raj",
     optionD:"Aryan",
     answer:"optionB",
  },
  {
    propmt:"What among the following did Phil wanted for his bday in the episode Game Changer?",
    optionA:"iPad",
    optionB:"iPhone",
    optionC:"self cleaning robot",
    optionD:"yogurt maker",
    answer:"optionA",
 },
 {
    propmt:"What is the name of Cameron Tucker's Clown name?",
    optionA:"Bozo",
    optionB:"Crusty",
    optionC:"Clown Tucker",
    optionD:"Fizbo",
    answer:"optionD",
 },
 {
    propmt:"Which is the birthplace of Lily?",
    optionA:"Thailand",
    optionB:"Singapore",
    optionC:"Vietnam",
    optionD:"South Korea",
    answer:"optionC",
 },
 {
   propmt:"What is the middle name of Hailey?",
   optionA:"Daisy",
   optionB:"Marie",
   optionC:"Elizabeth",
   optionD:"Gwendolyn",
   answer:"optionD",
},
{
   propmt:"Which university Luke got accepted into at the end?",
   optionA:"University of Oregon",
   optionB:"University of Michigan",
   optionC:"Colarado State University",
   optionD:"None",
   answer:"optionA",
},
{
   propmt:"Complete this Jay Pritchett's quote : `Look at Him.He's Like A Sherpa Crossed with A ____`?",
   optionA:"Chimpanzee",
   optionB:"Mountain Goat",
   optionC:"Great Dane",
   optionD:"Baguette",
   answer:"optionB",
},
{
   propmt:"Which fruit Gloria insists on eating 12 of them at the start of a new year?",
   optionA:"Grapes",
   optionB:"Strawberries",
   optionC:"Blueberries",
   optionD:"Peaches",
   answer:"optionA",
},
{
   propmt:"What is the nationality of Manny's girlfriend whom he meets during his cross-country journey ?",
   optionA:"Colombian",
   optionB:"American",
   optionC:"Canadian",
   optionD:"Brazilian",
   answer:"optionC",
},
{
   propmt:"What is the name of Claire's alter ego?",
   optionA:"Julianna",
   optionB:"Julie",
   optionC:"Jasmine",
   optionD:"Jade",
   answer:"optionA",
},
]